#Dico dédié a la commande choco (actuellement, possible autres utilisations dans le futur !)
dico = {
"1": "https://www.lafilleduboulanger.ca/wp-content/uploads/fdb-chocolatine.jpg",
"2": "https://www.lafilleduboulanger.ca/wp-content/uploads/fdb-chocolatine.jpg",
"3": "https://www.chocoblast.fr/wp-content/uploads/%C3%8Ates-vous-plut%C3%B4t-chocolatine-ou-pain-au-chocolat.jpg",
"4": "https://www.chocoblast.fr/wp-content/uploads/%C3%8Ates-vous-plut%C3%B4t-chocolatine-ou-pain-au-chocolat.jpg",
"5": "http://chokoalafraise.c.h.pic.centerblog.net/e5d59abf.png",
"6": "https://www.francetvinfo.fr/image/75it0saxe-08f3/1500/843/15108688.jpg",
"7": "https://www.telegraph.co.uk/content/dam/news/2018/05/24/TELEMMGLPICT000164508497_trans%2B%2BkZdGXfzOPVSbO-9sH583RFqaPefEGY05nXXPGqlPqGQ.jpeg",
"8": "https://www.parisvox.info/wp-content/uploads/2018/05/painauchocolat-950x400.jpg",
"10": "https://cache.cosmopolitan.fr/data/photo/w1000_ci/1bj/pain-au-chocolat-chocolatine.jpg",
"11": "https://www.lepoint.fr/images/2018/05/23/14952239lpw-14952489-article-des-pains-au-chocolat-aussi-appeles-chocolatine-jpg_5266450_540x282.jpg",
"12": "https://toulousesecret.com/wp-content/uploads/2022/02/Pain-au-chocolat-chocolatine-1024x682.jpg",
"13": "https://www.recette360.com/wp-content/uploads/2020/02/Chocolatine-au-thermomix.jpg",
"15": "https://www.radiofrance.fr/s3/cruiser-production/2022/04/f033dd25-d55c-42a0-a26d-291ac68d1b58/870x489_whatsapp_image_2022-04-26_at_12.31.11.jpg",
"16": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVyVGqSxnSxrFmHmz8ccSEaLQuKbGH6Xpjpl2qQc8PYFgW2Qnc4GHYXG8zqcHUqxSxkTk&usqp=CAU",
"17": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5kMtaW8ZaINFC9KmUzMSWBPHbFTE7JewqKA&usqp=CAU",
"18": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJydmOJpVDn8ZwkaPP6jM6ToTiUAAALzTtNQ&usqp=CAU",
"19": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSg80IULuG4mY2LahhoZjx7tqSEn5AQuOlJfw&usqp=CAU",
"20": "https://cdn.shopify.com/s/files/1/2385/1787/products/produits-a-decouvrir-boulangerie-viennoiseries-origines-choclatine-700x700.jpg?v=1643477243",
"21": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-_dHlwnuHNZBXNeY8EnTMFWHiUpbierJTBA&usqp=CAU",
"22": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0KyWXKcTZQI8K9KK7U6u8feUZvHkjxGmpeA&usqp=CAU",
"23": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSk0Vkg07gHELf1LxSVMgM9MvXd7-u1TkFXXg&usqp=CAU",
"24": "https://media.istockphoto.com/photos/chocolate-bread-picture-id519089853?k=20&m=519089853&s=612x612&w=0&h=286-QDHB_Lgirbl5opYuX6y17OxNyLR27QaeY5GIa9g=",
"25": "https://media.istockphoto.com/photos/chocolate-bread-picture-id1147511665?k=20&m=1147511665&s=612x612&w=0&h=JbjBdJWf6v04JnH6BXL1_HGKqYWPcZEJDrTpxbsRuQo=",
"26": "https://image.shutterstock.com/image-photo/freshly-backed-french-traditional-chocolate-260nw-1559824892.jpg",
"27": "https://media.istockphoto.com/photos/chocolate-bread-picture-id179287377?k=20&m=179287377&s=612x612&w=0&h=VoS3HbaDptR-14mEH0U4q7veJevB63D-58RUPu_3HdY=",
"28": "https://media.istockphoto.com/photos/chocolate-breads-picture-id1063635156?k=20&m=1063635156&s=612x612&w=0&h=38Sodu1a_wd2Hw1FezUfngVKmfCNL9TrOjVFRULv-9M=",
}
cristal_dico = {
    "1": "Je pense que oui.",
    "2": "Absolument !",
    "3": "Je ne pense pas.",
    "4": "Surtout pas !",
    "5": "Pourquoi pas ?",
    "6": "Les astres sonts troublés, réésaye plus tard.",
    "7": "oui",
    "8": "non,"
}
joke_dico = {
    "1": "Quelle mamie fait peur aux voleurs ?\n Mamie Traillette.  ",
    "2": "J'ai une blague sur les magasins\n Mais elle a pas supermarché",
    "3": "Pourquoi est-ce c'est difficile de conduire dans le Nord ?\n Parce que les voitures arrêtent PAS DE CALER.",
    "4": "Deux lions discutent\n « T’as une belle crinière »\n « Arrête, tu vas me faire rugir »",
    "5": "Pourquoi est-ce qu'on dit que les bretons sont tous frères et sœurs ?\n Parce qu’ils n’ont Quimper.",
    "6": "Pourquoi est-ce qu'on met tous les crocos en prison ?\n  Parce que les crocos dealent.",
    "7": "Comment fait-on pour allumer un barbecue breton ?\n On utilise des breizh.",
    "8": "Pourquoi dit-on que les poissons travaillent illégalement ?\n Parce qu’ils n’ont pas de FISH de paie.",
    "9": "Quel est le bar préféré des espagnols ?\n Le Bar-celone",
    "10": "Que faisaient les dinosaures quand ils n'arrivaient pas à se décider?\n Des tirageosaures",
    "11": "Qu'est-ce qu'un tennisman adore faire ?\n Rendre des services",
    "12": "Pourquoi est-ce que les vêtements sont toujours fatigués quand ils sortent de la machine ?\n Parce qu’ils sont léssivés",
    "13": "Pourquoi est-ce que les livres ont-ils toujours chaud ?\n Parce qu’ils ont une couverture",
    "15": "Où est-ce que les super héros vont-ils faire leurs courses ?\n Au supermarché",
    "16": "Que se passe-t-il quand 2 poissons s'énervent ?\n Le thon monte",
    "17": "Quel fruit est assez fort pour couper des arbres?\n Le ci-tron",
    "18": "Quel est le jambon que tout le monde déteste ?\n Le sale ami",
    "29": "Que fait un cendrier devant un ascenseur ?\n Il veut des cendres",
    "20": "Que dit une imprimante dans l'eau ?\n J'ai papier",
    "21": "Un chameau dit à un dromadaire :\n « Comment ça va ? »\n « Bien, je bosse, et toi ? »\n « Je bosse, je bosse. » ",
    "22": "Quel est l'aliment le plus hilarant?\n Le riz",
    "23": "C’est une jolie petite antenne de T.V. qui est tombée amoureuse d’un paratonnerre...\n Elle lui dit : Dis, tu y crois toi, au coup de foudre ?",
    "24": "Quel est le sport préféré des insectes?\n Le criquet",
    "25": "Deux souris voient passer une chauve-souris\n « Regarde, un ange ! »",
}
banned_words = [
    "pain au chocolat",
    "pain au choco",
    "pain  au  chocolat",
    "painauchocolat",
    "pain au chocola",
    "phrase de test 1234",
]


